name: "HCL AppScan SAST"
on:
  pull
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST Scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.6
        with:
          service_url:  https://cloud.appscan.com/
          asoc_key: ${{secrets.ASOC_CONSULTANT_KEY}}
          asoc_secret: ${{secrets.ASOC_CONSULTANT_SECRET}}
          application_id: ${{vars.ASOC_APPID_SAST}}
          wait_for_analysis: true
          fail_for_noncompliance: true
          failure_threshold: Medium
      - name: Upload HCL AppScan HTML Report to Github Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AppScan Security Scan HTML Report 
          path: '**/Repport*.html'
        if: success() || failure()

